In [1]:
#imports 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import HistGradientBoostingClassifier

In [2]:
df=pd.read_csv("fetal_health.csv")
print(df.index)
print("All columns are")
ai=0
for i in df:
    print(ai,i)
    ai+=1

RangeIndex(start=0, stop=2126, step=1)
All columns are
0 baseline value
1 accelerations
2 fetal_movement
3 uterine_contractions
4 light_decelerations
5 severe_decelerations
6 prolongued_decelerations
7 abnormal_short_term_variability
8 mean_value_of_short_term_variability
9 percentage_of_time_with_abnormal_long_term_variability
10 mean_value_of_long_term_variability
11 histogram_width
12 histogram_min
13 histogram_max
14 histogram_number_of_peaks
15 histogram_number_of_zeroes
16 histogram_mode
17 histogram_mean
18 histogram_median
19 histogram_variance
20 histogram_tendency
21 fetal_health


In [3]:
df.shape

(2126, 22)

In [4]:
df.head(n=10)

,baseline value,accelerations,fetal_movement,uterine_contractions,light_decelerations,severe_decelerations,prolongued_decelerations,abnormal_short_term_variability,mean_value_of_short_term_variability,percentage_of_time_with_abnormal_long_term_variability,...,histogram_min,histogram_max,histogram_number_of_peaks,histogram_number_of_zeroes,histogram_mode,histogram_mean,histogram_median,histogram_variance,histogram_tendency,fetal_health
0,120.0,0.000,0.0,0.000,0.000,0.0,0.000,73.0,0.5,43.0,...,62.0,126.0,2.0,0.0,120.0,137.0,121.0,73.0,1.0,2.0
1,132.0,0.006,0.0,0.006,0.003,0.0,0.000,17.0,2.1,0.0,...,68.0,198.0,6.0,1.0,141.0,136.0,140.0,12.0,0.0,1.0
2,133.0,0.003,0.0,0.008,0.003,0.0,0.000,16.0,2.1,0.0,...,68.0,198.0,5.0,1.0,141.0,135.0,138.0,13.0,0.0,1.0
3,134.0,0.003,0.0,0.008,0.003,0.0,0.000,16.0,2.4,0.0,...,53.0,170.0,11.0,0.0,137.0,134.0,137.0,13.0,1.0,1.0
4,132.0,0.007,0.0,0.008,0.000,0.0,0.000,16.0,2.4,0.0,...,53.0,170.0,9.0,0.0,137.0,136.0,138.0,11.0,1.0,1.0
5,134.0,0.001,0.0,0.010,0.009,0.0,0.002,26.0,5.9,0.0,...,50.0,200.0,5.0,3.0,76.0,107.0,107.0,170.0,0.0,3.0
6,134.0,0.001,0.0,0.013,0.008,0.0,0.003,29.0,6.3,0.0,...,50.0,200.0,6.0,3.0,71.0,107.0,106.0,215.0,0.0,3.0
7,122.0,0.000,0.0,0.000,0.000,0.0,0.000,83.0,0.5,6.0,...,62.0,130.0,0.0,0.0,122.0,122.0,123.0,3.0,1.0,3.0
8,122.0,0.000,0.0,0.002,0.000,0.0,0.000,84.0,0.5,5.0,...,62.0,130.0,0.0,0.0,122.0,122.0,123.0,3.0,1.0,3.0
9,122.0,0.000,0.0,0.003,0.000,0.0,0.000,86.0,0.3,6.0,...,62.0,130.0,1.0,0.0,122.0,122.0,123.0,1.0,1.0,3.0


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability  

In [6]:
df.describe()

,baseline value,accelerations,fetal_movement,uterine_contractions,light_decelerations,severe_decelerations,prolongued_decelerations,abnormal_short_term_variability,mean_value_of_short_term_variability,percentage_of_time_with_abnormal_long_term_variability,...,histogram_min,histogram_max,histogram_number_of_peaks,histogram_number_of_zeroes,histogram_mode,histogram_mean,histogram_median,histogram_variance,histogram_tendency,fetal_health
count,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000,2126.00000,...,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000,2126.000000
mean,133.303857,0.003178,0.009481,0.004366,0.001889,0.000003,0.000159,46.990122,1.332785,9.84666,...,93.579492,164.025400,4.068203,0.323612,137.452023,134.610536,138.090310,18.808090,0.320320,1.304327
std,9.840844,0.003866,0.046666,0.002946,0.002960,0.000057,0.000590,17.192814,0.883241,18.39688,...,29.560212,17.944183,2.949386,0.706059,16.381289,15.593596,14.466589,28.977636,0.610829,0.614377
min,106.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,0.200000,0.00000,...,50.000000,122.000000,0.000000,0.000000,60.000000,73.000000,77.000000,0.000000,-1.000000,1.000000
25%,126.000000,0.000000,0.000000,0.002000,0.000000,0.000000,0.000000,32.000000,0.700000,0.00000,...,67.000000,152.000000,2.000000,0.000000,129.000000,125.000000,129.000000,2.000000,0.000000,1.000000
50%,133.000000,0.002000,0.000000,0.004000,0.000000,0.000000,0.000000,49.000000,1.200000,0.00000,...,93.000000,162.000000,3.000000,0.000000,139.000000,136.000000,139.000000,7.000000,0.000000,1.000000
75%,140.000000,0.006000,0.003000,0.007000,0.003000,0.000000,0.000000,61.000000,1.700000,11.00000,...,120.000000,174.000000,6.000000,0.000000,148.000000,145.000000,148.000000,24.000000,1.000000,1.000000
max,160.000000,0.019000,0.481000,0.015000,0.015000,0.001000,0.005000,87.000000,7.000000,91.00000,...,159.000000,238.000000,18.000000,10.000000,187.000000,182.000000,186.000000,269.000000,1.000000,3.000000


In [7]:
# Gradient Boosting
X = df.drop("fetal_health", axis=1)
y = df["fetal_health"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

gb.fit(X_train, y_train)

y_pred = gb.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9272300469483568

Classification Report:
              precision    recall  f1-score   support

         1.0       0.95      0.97      0.96       332
         2.0       0.85      0.68      0.75        59
         3.0       0.84      0.91      0.88        35

    accuracy                           0.93       426
   macro avg       0.88      0.86      0.86       426
weighted avg       0.93      0.93      0.92       426


Confusion Matrix:
[[323   6   3]
 [ 16  40   3]
 [  2   1  32]]


In [8]:
scores = cross_val_score(
    gb,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("CV Scores:", scores)
print("Mean CV Accuracy:", scores.mean())

CV Scores: [0.91314554 0.94823529 0.94117647 0.91058824 0.74352941]
Mean CV Accuracy: 0.8913349903341619


In [9]:
params = {
    "n_estimators": [100, 300],
    "learning_rate": [0.05, 0.1],
    "max_depth": [3, 7],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 4]
}

grid = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    param_grid=params,
    cv=3,
    scoring="accuracy",
    n_jobs=-1,
    return_train_score=True
)

grid.fit(X_train, y_train)

print("Best Parameters:")
print(grid.best_params_)

print("\nBest CV Score:")
print(grid.best_score_)

Best Parameters:
{'learning_rate': 0.1, 'max_depth': 7, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300}

Best CV Score:
0.9576449521482894


In [10]:
results = pd.DataFrame(grid.cv_results_)

top_results = (
    results[
        [
            "mean_train_score",
            "mean_test_score",
            "param_n_estimators",
            "param_learning_rate",
            "param_max_depth",
            "param_min_samples_split",
            "param_min_samples_leaf"
        ]
    ]
    .sort_values("mean_test_score", ascending=False)
)

top_results.head(10)

,mean_train_score,mean_test_score,param_n_estimators,param_learning_rate,param_max_depth,param_min_samples_split,param_min_samples_leaf
37,0.999412,0.957645,300,0.10,7,2,1
39,0.999412,0.956470,300,0.10,7,5,1
27,0.999412,0.954116,300,0.10,3,5,1
47,0.999412,0.953531,300,0.10,7,10,4
45,0.999412,0.953531,300,0.10,7,5,4
43,0.999412,0.953531,300,0.10,7,2,4
29,0.999412,0.953530,300,0.10,3,10,1
41,0.999412,0.953529,300,0.10,7,10,1
21,0.999412,0.952943,300,0.05,7,5,4
46,0.999412,0.952943,100,0.10,7,10,4


In [11]:
# again using previous as guide
params = {
    "n_estimators": [400,500],
    "learning_rate": [0.2,0.3],
    "max_depth": [10,15],
    "min_samples_split": [1,3],
    "min_samples_leaf": [1]
}

grid = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    param_grid=params,
    cv=3,
    scoring="accuracy",
    n_jobs=-1,
    return_train_score=True
)

grid.fit(X_train, y_train)

print("Best Parameters:")
print(grid.best_params_)

print("\nBest CV Score:")
print(grid.best_score_)

C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
24 fits failed out of a total of 48.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
24 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\abhinavkuriya\anaconda3\Lib\site-packages\sklearn\base.py", li

Best Parameters:
{'learning_rate': 0.2, 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 3, 'n_estimators': 500}

Best CV Score:
0.9482376818458483


In [12]:
results = pd.DataFrame(grid.cv_results_)

top_results = (
    results[
        [
            "mean_train_score",
            "mean_test_score",
            "param_n_estimators",
            "param_learning_rate",
            "param_max_depth",
            "param_min_samples_split",
            "param_min_samples_leaf"
        ]
    ]
    .sort_values("mean_test_score", ascending=False)
)

top_results.head(10)

,mean_train_score,mean_test_score,param_n_estimators,param_learning_rate,param_max_depth,param_min_samples_split,param_min_samples_leaf
3,0.999412,0.948238,500,0.2,10,3,1
2,0.999412,0.947650,400,0.2,10,3,1
11,0.999412,0.947650,500,0.3,10,3,1
10,0.999412,0.947062,400,0.3,10,3,1
14,0.999412,0.936480,400,0.3,15,3,1
15,0.999412,0.935892,500,0.3,15,3,1
7,0.999412,0.935890,500,0.2,15,3,1
6,0.999412,0.935301,400,0.2,15,3,1
0,NaN,NaN,400,0.2,10,1,1
1,NaN,NaN,500,0.2,10,1,1
